import { useMemo, useState } from 'react'
import { Activity, AlertTriangle, Bell, Boxes, Building2, ChevronDown, CircleDollarSign, Code2, CreditCard, Database, FileCog, Globe2, KeyRound, Landmark, LayoutDashboard, Menu, Network, Palette, Plus, RefreshCw, Search, Settings, ShieldCheck, Users, WalletCards, Webhook, X, CheckCircle2, LogOut } from 'lucide-react'

type NavId='overview'|'tenants'|'whitelabel'|'programs'|'funds'|'revenue'|'sandbox'|'api'|'operations'|'risk'|'system'
type Toast={text:string;type:'ok'|'warn'}|null

type Tenant={id:string;name:string;country:string;model:'White Label'|'OEM'|'ODM';status:'运行中'|'审核中'|'暂停';users:number;cards:number;volume:number;kyb:string;brand:string}
type Program={id:string;tenant:string;name:string;scheme:string;type:string;status:string;issued:number;bin:string}

const nav=[
{id:'overview' as NavId,label:'平台总览',icon:LayoutDashboard},{id:'tenants' as NavId,label:'租户与合作方',icon:Building2,badge:3},{id:'whitelabel' as NavId,label:'白标 / OEM / ODM',icon:Palette},{id:'programs' as NavId,label:'卡项目管理',icon:CreditCard},{id:'funds' as NavId,label:'资金池与清算',icon:Landmark},{id:'revenue' as NavId,label:'费率与收入分成',icon:CircleDollarSign},{id:'sandbox' as NavId,label:'Developer Sandbox',icon:Code2},{id:'api' as NavId,label:'API 与 Webhook',icon:Webhook},{id:'operations' as NavId,label:'终端用户运营',icon:Users},{id:'risk' as NavId,label:'风控与合规',icon:ShieldCheck,badge:6},{id:'system' as NavId,label:'系统与权限',icon:Settings}]

const seedTenants:Tenant[]=[
{id:'TEN-1001',name:'NovaPay Asia',country:'新加坡',model:'White Label',status:'运行中',users:12840,cards:7310,volume:4286000,kyb:'已通过',brand:'NovaPay'},
{id:'TEN-1002',name:'Orbit Card Labs',country:'马来西亚',model:'OEM',status:'运行中',users:6820,cards:3980,volume:1865000,kyb:'已通过',brand:'Orbit'},
{id:'TEN-1003',name:'BluePeak Finance',country:'香港',model:'ODM',status:'审核中',users:0,cards:0,volume:0,kyb:'补件中',brand:'BluePeak'},
{id:'TEN-1004',name:'Astra Global',country:'阿联酋',model:'White Label',status:'暂停',users:3210,cards:1750,volume:642000,kyb:'已通过',brand:'Astra'}]

const seedPrograms:Program[]=[
{id:'PRG-001',tenant:'NovaPay Asia',name:'NovaPay Global U Card',scheme:'Mastercard',type:'虚拟卡 + 实体卡',status:'生产模拟',issued:7310,bin:'5239 88'},
{id:'PRG-002',tenant:'Orbit Card Labs',name:'Orbit Travel Card',scheme:'Mastercard',type:'虚拟卡',status:'Sandbox',issued:3980,bin:'5239 91'},
{id:'PRG-003',tenant:'BluePeak Finance',name:'BluePeak Premium',scheme:'Mastercard',type:'实体卡',status:'配置中',issued:0,bin:'待分配'}]

const apiClients=[
{id:'API-NOVA-01',tenant:'NovaPay Asia',env:'Production Mock',scope:'cards wallets transactions',status:'Active',requests:'1.28M'},
{id:'API-ORBIT-01',tenant:'Orbit Card Labs',env:'Sandbox',scope:'cards kyc webhooks',status:'Active',requests:'384K'},
{id:'API-BLUE-01',tenant:'BluePeak Finance',env:'Sandbox',scope:'onboarding cards',status:'Suspended',requests:'8.4K'}]

function money(n:number){return `$${n.toLocaleString(undefined,{maximumFractionDigits:0})}`}
function Tag({v}:{v:string}){return <span className={`status tag-${v.replaceAll(' ','-')}`}>{v}</span>}

export default function App(){
 const[active,setActive]=useState<NavId>('overview');const[mobile,setMobile]=useState(false);const[query,setQuery]=useState('');const[toast,setToast]=useState<Toast>(null)
 const[tenantView,setTenantView]=useState('FastLink Platform');const[tenants,setTenants]=useState(seedTenants);const[programs,setPrograms]=useState(seedPrograms)
 const[reserve,setReserve]=useState({usdt:18420000,fiat:3860000,settlement:428600,merchant:214000});const[sandboxRuns,setSandboxRuns]=useState(1284)
 const notify=(text:string,type:'ok'|'warn'='ok')=>{setToast({text,type});setTimeout(()=>setToast(null),2200)}
 const current=nav.find(x=>x.id===active)!
 const filteredTenants=useMemo(()=>tenants.filter(t=>`${t.id} ${t.name} ${t.country} ${t.model} ${t.status}`.toLowerCase().includes(query.toLowerCase())),[tenants,query])
 const switchPage=(id:NavId)=>{setActive(id);setMobile(false)}
 const addTenant=()=>{const n=tenants.length+1;setTenants(v=>[...v,{id:`TEN-10${n}`,name:`New Partner ${n}`,country:'待设置',model:'White Label',status:'审核中',users:0,cards:0,volume:0,kyb:'待提交',brand:`Partner ${n}`}]);notify('已创建新的测试租户')}
 const toggleTenant=(id:string)=>{setTenants(v=>v.map(t=>t.id===id?{...t,status:t.status==='暂停'?'运行中':'暂停'}:t));notify('租户状态已更新')}
 const settle=()=>{setReserve(v=>({...v,fiat:v.fiat-v.settlement,settlement:0}));notify('测试清算批次已完成')}
 return <div className="app-shell">
  <aside className={`sidebar ${mobile?'open':''}`}><div className="brand"><div className="brand-mark">F</div><div><b>FastLink</b><span>FINANCIAL SAAS CONTROL</span></div><button className="mobile-close" onClick={()=>setMobile(false)}><X/></button></div><div className="sandbox-badge"><i/>SaaS Sandbox · 多租户模拟数据</div><nav>{nav.map(({id,label,icon:Icon,badge})=><button key={id} className={active===id?'active':''} onClick={()=>switchPage(id)}><Icon size={18}/><span>{label}</span>{badge&&<em>{badge}</em>}</button>)}</nav><div className="sidebar-foot"><div className="system-dot"><i/>所有测试服务正常</div><button><LogOut size={17}/>退出登录</button></div></aside>
  {mobile&&<div className="scrim" onClick={()=>setMobile(false)}/>}<main><header className="topbar"><div className="title-wrap"><button className="menu-btn" onClick={()=>setMobile(true)}><Menu/></button><div><h1>{current.label}</h1><p>FastLink Financial SaaS Platform · Sandbox V1</p></div></div><div className="top-actions"><select className="tenant-select" value={tenantView} onChange={e=>setTenantView(e.target.value)}><option>FastLink Platform</option>{tenants.map(t=><option key={t.id}>{t.name}</option>)}</select><label className="search-box"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索租户、卡项目、用户..."/></label><button className="icon-btn"><Bell size={18}/><i/></button></div></header><div className="page-content">
  {active==='overview'&&<Overview tenants={tenants} reserve={reserve} setActive={switchPage}/>} 
  {active==='tenants'&&<Tenants rows={filteredTenants} add={addTenant} toggle={toggleTenant} notify={notify}/>} 
  {active==='whitelabel'&&<WhiteLabel notify={notify}/>} 
  {active==='programs'&&<Programs rows={programs} setRows={setPrograms} notify={notify}/>} 
  {active==='funds'&&<Funds reserve={reserve} setReserve={setReserve} settle={settle} notify={notify}/>} 
  {active==='revenue'&&<Revenue notify={notify}/>} 
  {active==='sandbox'&&<Sandbox runs={sandboxRuns} setRuns={setSandboxRuns} notify={notify}/>} 
  {active==='api'&&<ApiCenter notify={notify}/>} 
  {active==='operations'&&<Operations notify={notify}/>} 
  {active==='risk'&&<Risk notify={notify}/>} 
  {active==='system'&&<System notify={notify}/>} 
  </div></main>{toast&&<div className={`toast ${toast.type}`}>{toast.type==='ok'?<CheckCircle2/>:<AlertTriangle/>}{toast.text}</div>}</div>
}

function Header({title,desc,label,action}:{title:string;desc:string;label?:string;action?:()=>void}){return <div className="page-head"><div><h2>{title}</h2><p>{desc}</p></div>{action&&<button className="primary-btn" onClick={action}><Plus size={16}/>{label}</button>}</div>}
function Stat({label,value,sub}:{label:string;value:string;sub:string}){return <article className="metric-card"><span>{label}</span><strong>{value}</strong><small>{sub}</small></article>}

function Overview({tenants,reserve,setActive}:{tenants:Tenant[];reserve:any;setActive:(n:NavId)=>void}){return <><section className="hero saas-hero"><div><span>FASTLINK PLATFORM CONTROL PLANE</span><h2>多租户金融 SaaS 运营中枢</h2><p>统一管理白标、OEM、ODM、U卡发行、钱包、支付、换汇、清算与合作方开放平台。</p></div><button className="primary-btn" onClick={()=>setActive('tenants')}>管理合作方</button></section><section className="metrics-grid"><Stat label="活跃租户" value={`${tenants.filter(t=>t.status==='运行中').length}`} sub="4 个已签约项目"/><Stat label="终端用户" value="22,870" sub="跨 4 个租户"/><Stat label="已发行卡片" value="13,040" sub="虚拟卡与实体卡"/><Stat label="月度平台收入" value="$428,600" sub="SaaS费 + 发卡 + 分成"/></section><section className="content-grid"><article className="panel"><div className="panel-title"><div><h3>租户经营表现</h3><p>按交易规模和卡片发行量排序</p></div></div><table><thead><tr><th>合作方</th><th>模式</th><th>用户</th><th>卡片</th><th>交易额</th><th>状态</th></tr></thead><tbody>{tenants.map(t=><tr key={t.id}><td><b>{t.name}</b><small className="cell-sub">{t.country}</small></td><td>{t.model}</td><td>{t.users.toLocaleString()}</td><td>{t.cards.toLocaleString()}</td><td>{money(t.volume)}</td><td><Tag v={t.status}/></td></tr>)}</tbody></table></article><article className="panel"><div className="panel-title"><div><h3>平台资金与清算</h3><p>模拟总资金视图</p></div></div><div className="fund-stack"><div><span>公司 USDT 资金池</span><b>{money(reserve.usdt)}</b></div><div><span>Sponsor Bank 法币准备金</span><b>{money(reserve.fiat)}</b></div><div><span>待清算敞口</span><b>{money(reserve.settlement)}</b></div><div><span>商户支付备付金</span><b>{money(reserve.merchant)}</b></div></div><button className="wide-btn" onClick={()=>setActive('funds')}>进入 Treasury 控制中心</button></article></section><section className="three-grid"><Mini title="发卡基础设施" icon={<CreditCard/>} lines={['Thredd Sandbox：正常','Mastercard Program：3','Tokenization：测试中']}/><Mini title="支付与换汇" icon={<RefreshCw/>} lines={['FOMO Pay Adapter：正常','USDT/法币编排：正常','多币种账本：正常']}/><Mini title="开放平台" icon={<Network/>} lines={['API Clients：3','Webhook成功率：99.82%','Sandbox租户：4']}/></section></>}
function Mini({title,icon,lines}:{title:string;icon:any;lines:string[]}){return <article className="panel mini"><div className="mini-head">{icon}<b>{title}</b></div>{lines.map(x=><p key={x}><i/>{x}</p>)}</article>}

function Tenants({rows,add,toggle,notify}:{rows:Tenant[];add:()=>void;toggle:(id:string)=>void;notify:(s:string)=>void}){return <><Header title="租户与合作方" desc="管理合作方入驻、KYB、合同、保证金、授信和多级组织关系。" label="新增合作方" action={add}/><section className="module-stats"><Stat label="签约租户" value="4" sub="3个运行中"/><Stat label="KYB待处理" value="3" sub="含补件与复核"/><Stat label="保证金总额" value="$1.42M" sub="模拟数据"/></section><article className="panel"><table><thead><tr><th>租户</th><th>业务模式</th><th>KYB</th><th>终端用户</th><th>卡片</th><th>交易额</th><th>状态</th><th>操作</th></tr></thead><tbody>{rows.map(t=><tr key={t.id}><td><b>{t.name}</b><small className="cell-sub">{t.id} · {t.country}</small></td><td>{t.model}</td><td><Tag v={t.kyb}/></td><td>{t.users.toLocaleString()}</td><td>{t.cards.toLocaleString()}</td><td>{money(t.volume)}</td><td><Tag v={t.status}/></td><td><button className="text-btn" onClick={()=>notify(`已进入 ${t.name} 租户控制台`)}>进入</button><button className="text-btn danger" onClick={()=>toggle(t.id)}>{t.status==='暂停'?'恢复':'暂停'}</button></td></tr>)}</tbody></table></article></>}

function WhiteLabel({notify}:{notify:(s:string)=>void}){const projects=[['NovaPay','White Label','App + H5 + Admin','已发布'],['Orbit','OEM','App + Card Design','验收中'],['BluePeak','ODM','Product + Tech + Operations','配置中']];return <><Header title="白标 / OEM / ODM 项目" desc="配置品牌、域名、Logo、主题、语言、卡面、App、H5和运营交付范围。" label="创建交付项目" action={()=>notify('已创建新的白标交付项目')}/><section className="three-grid">{projects.map(p=><article className="panel project-card" key={p[0]}><div className="project-logo">{p[0][0]}</div><h3>{p[0]}</h3><Tag v={p[1]}/><p>{p[2]}</p><div className="progress"><i style={{width:p[3]==='已发布'?'100%':p[3]==='验收中'?'76%':'42%'}}/></div><b>{p[3]}</b><button className="wide-btn" onClick={()=>notify(`打开 ${p[0]} 品牌配置器`)}>打开品牌配置器</button></article>)}</section><article className="panel config-grid"><Config title="品牌资产" icon={<Palette/>} items={['Logo与品牌名','主题色与字体','多语言文案']}/><Config title="渠道交付" icon={<Globe2/>} items={['App / H5','独立域名','管理后台']}/><Config title="卡产品" icon={<CreditCard/>} items={['卡面设计','卡等级','费率与限额']}/><Config title="服务范围" icon={<FileCog/>} items={['技术交付','运营托管','合规支持']}/></article></>}
function Config({title,icon,items}:{title:string;icon:any;items:string[]}){return <div><span className="config-icon">{icon}</span><b>{title}</b>{items.map(x=><p key={x}>• {x}</p>)}</div>}

function Programs({rows,setRows,notify}:{rows:Program[];setRows:any;notify:(s:string)=>void}){const add=()=>{setRows((v:Program[])=>[...v,{id:`PRG-00${v.length+1}`,tenant:'New Partner',name:'New U Card Program',scheme:'Mastercard',type:'虚拟卡',status:'配置中',issued:0,bin:'待分配'}]);notify('已创建新的测试卡项目')};return <><Header title="卡项目管理" desc="管理BIN Program、卡产品、费率、限额、虚拟卡、实体卡和处理商路由。" label="创建卡项目" action={add}/><article className="panel"><table><thead><tr><th>Program</th><th>租户</th><th>卡产品</th><th>卡组织</th><th>BIN</th><th>发行量</th><th>状态</th><th>操作</th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><b>{p.name}</b><small className="cell-sub">{p.id}</small></td><td>{p.tenant}</td><td>{p.type}</td><td>{p.scheme}</td><td>{p.bin}</td><td>{p.issued.toLocaleString()}</td><td><Tag v={p.status}/></td><td><button className="text-btn" onClick={()=>notify(`已打开 ${p.name} Program Builder`)}>配置</button></td></tr>)}</tbody></table></article></>}

function Funds({reserve,setReserve,settle,notify}:{reserve:any;setReserve:any;settle:()=>void;notify:(s:string)=>void}){const allocate=()=>{setReserve((v:any)=>({...v,fiat:v.fiat+250000,usdt:v.usdt-250000}));notify('已完成模拟资金调拨')};return <><Header title="资金池、流动性与清算" desc="统一控制USDT资金池、法币准备金、租户子账户、清算批次和通道敞口。"/><section className="metrics-grid"><Stat label="USDT资金池" value={money(reserve.usdt)} sub="公司主资金池"/><Stat label="法币准备金" value={money(reserve.fiat)} sub="Sponsor Bank"/><Stat label="待清算" value={money(reserve.settlement)} sub="下一批次"/><Stat label="流动性覆盖率" value="428%" sub="高于警戒线"/></section><section className="content-grid"><article className="panel"><h3>租户资金子账户</h3>{[['NovaPay','$2.14M','78%'],['Orbit','$886K','64%'],['Astra','$214K','42%']].map(x=><div className="liquidity" key={x[0]}><div><b>{x[0]}</b><span>{x[1]}</span></div><div className="progress"><i style={{width:x[2]}}/></div><small>覆盖率 {x[2]}</small></div>)}</article><article className="panel action-panel"><h3>Treasury 操作</h3><button className="primary-btn" onClick={allocate}>调拨 $250,000</button><button className="wide-btn" onClick={settle}>执行测试清算批次</button><button className="wide-btn" onClick={()=>notify('已生成供应商对账文件')}>生成供应商对账</button></article></section></>}

function Revenue({notify}:{notify:(s:string)=>void}){return <><Header title="费率、账单与收入分成" desc="管理SaaS订阅费、发卡费、充值费、换汇点差、交易分成和多级代理佣金。" label="新建费率模板" action={()=>notify('已创建新的费率模板')}/><section className="metrics-grid"><Stat label="本月平台收入" value="$428,600" sub="+18.4% 环比"/><Stat label="合作方应结算" value="$186,420" sub="4个租户"/><Stat label="换汇点差收入" value="$92,840" sub="USDT / 法币"/><Stat label="卡业务收入" value="$149,340" sub="发卡与交易"/></section><article className="panel"><table><thead><tr><th>租户</th><th>SaaS月费</th><th>发卡费</th><th>交易分成</th><th>换汇点差</th><th>本月收入</th><th>结算状态</th></tr></thead><tbody>{[['NovaPay','$18,000','$2.50','0.42%','0.80%','$248,600','待结算'],['Orbit','$12,000','$2.10','0.38%','0.70%','$126,400','已结算'],['Astra','$8,000','$2.80','0.45%','0.85%','$53,600','审核中']].map(r=><tr key={r[0]}>{r.map((c,i)=><td key={i}>{i===0?<b>{c}</b>:i===6?<Tag v={c}/>:c}</td>)}</tr>)}</tbody></table></article></>}

function Sandbox({runs,setRuns,notify}:{runs:number;setRuns:any;notify:(s:string)=>void}){const run=()=>{setRuns((n:number)=>n+1);notify('已执行完整发卡测试流程')};return <><Header title="Developer Sandbox" desc="为合作方提供隔离测试租户、模拟用户、测试卡、Webhook回放和完整业务场景。" label="新建Sandbox租户" action={()=>notify('已创建隔离Sandbox租户')}/><section className="metrics-grid"><Stat label="Sandbox租户" value="4" sub="完全隔离"/><Stat label="本月测试调用" value={runs.toLocaleString()} sub="API + Webhook"/><Stat label="测试卡" value="286" sub="虚拟卡与实体卡"/><Stat label="成功率" value="99.82%" sub="过去30天"/></section><section className="three-grid"><Scenario title="用户开户与KYC" steps="Create User → KYC Review → Wallet" run={run}/><Scenario title="U卡发行全流程" steps="Top-up → FX → Issue Card → Authorize" run={run}/><Scenario title="清算与冲正" steps="Clearing → Settlement → Reversal" run={run}/></section><article className="panel"><h3>Sandbox 服务状态</h3><div className="service-grid">{['Identity Service','Wallet Ledger','Card Adapter','FX Orchestrator','Webhook Gateway','Settlement Engine'].map(x=><div key={x}><i/>{x}<b>Healthy</b></div>)}</div></article></>}
function Scenario({title,steps,run}:{title:string;steps:string;run:()=>void}){return <article className="panel scenario"><Code2/><h3>{title}</h3><p>{steps}</p><button className="wide-btn" onClick={run}>运行测试场景</button></article>}

function ApiCenter({notify}:{notify:(s:string)=>void}){return <><Header title="API、Webhook 与开发者管理" desc="管理API Client、Key、Scope、签名密钥、回调地址、幂等和事件投递。" label="创建API Client" action={()=>notify('已生成新的测试API Client')}/><article className="panel"><table><thead><tr><th>Client</th><th>租户</th><th>环境</th><th>Scope</th><th>请求量</th><th>状态</th><th>操作</th></tr></thead><tbody>{apiClients.map(a=><tr key={a.id}><td><b>{a.id}</b></td><td>{a.tenant}</td><td>{a.env}</td><td>{a.scope}</td><td>{a.requests}</td><td><Tag v={a.status}/></td><td><button className="text-btn" onClick={()=>notify('测试密钥已轮换')}>轮换密钥</button></td></tr>)}</tbody></table></article><section className="content-grid"><article className="panel"><h3>Webhook投递</h3><div className="fund-stack"><div><span>成功</span><b>98,284</b></div><div><span>重试中</span><b>42</b></div><div><span>死信队列</span><b>6</b></div></div><button className="wide-btn" onClick={()=>notify('已回放失败Webhook事件')}>回放失败事件</button></article><article className="panel"><h3>开发者安全</h3><p className="note"><KeyRound/>API Key仅显示一次，所有请求启用HMAC签名、时间戳校验、幂等键和IP白名单。</p><button className="wide-btn" onClick={()=>notify('安全策略已保存')}>保存安全策略</button></article></section></>}

function Operations({notify}:{notify:(s:string)=>void}){return <><Header title="终端用户运营子系统" desc="现有用户、KYC、钱包、卡片、交易和Tokenization功能被保留在租户运营层。"/><section className="six-grid">{[['用户与KYC',Users,'22,870'],['钱包账户',WalletCards,'$8.42M'],['卡片管理',CreditCard,'13,040'],['交易管理',Activity,'284K'],['Tokenization',Boxes,'1,842'],['客户工单',Bell,'38']].map(([t,I,v]:any)=><article className="panel op-card" key={t}><I/><b>{t}</b><strong>{v}</strong><button className="text-btn" onClick={()=>notify(`已打开 ${t} 租户运营视图`)}>进入模块</button></article>)}</section></>}
function Risk({notify}:{notify:(s:string)=>void}){return <><Header title="跨租户风控与合规" desc="平台级AML、异常交易、租户风险、卡项目风险、规则引擎和案件协同。"/><section className="metrics-grid"><Stat label="开放案件" value="6" sub="2个高风险"/><Stat label="今日拦截" value="$184,200" sub="模拟金额"/><Stat label="KYB复核" value="3" sub="合作方层级"/><Stat label="规则命中" value="128" sub="过去24小时"/></section><article className="panel"><table><thead><tr><th>案件</th><th>租户</th><th>主体</th><th>规则</th><th>评分</th><th>状态</th><th>操作</th></tr></thead><tbody>{[['RSK-01','NovaPay','User FLU-8821','短时大额授权','92','待处理'],['RSK-02','Orbit','Merchant M-118','高频退款','78','调查中'],['RSK-03','Astra','Tenant Account','保证金不足','88','已限制']].map(r=><tr key={r[0]}>{r.map((c,i)=><td key={i}>{i===5?<Tag v={c}/>:c}</td>)}<td><button className="text-btn" onClick={()=>notify('案件已分配给合规专员')}>处理</button></td></tr>)}</tbody></table></article></>}
function System({notify}:{notify:(s:string)=>void}){return <><Header title="系统、权限与审计" desc="管理平台RBAC、租户级权限、环境开关、供应商适配器和审计日志。"/><section className="three-grid"><article className="panel"><h3>角色权限</h3>{['Platform Super Admin','Treasury Operator','Compliance Officer','Tenant Admin'].map(x=><p key={x}><ShieldCheck size={15}/>{x}</p>)}</article><article className="panel"><h3>供应商适配器</h3>{['Thredd Adapter','FOMO Pay Adapter','Sponsor Bank Adapter','KYC Adapter'].map(x=><p key={x}><i className="health"/>{x}</p>)}</article><article className="panel"><h3>环境控制</h3>{['Sandbox发卡','Webhook回放','模拟清算','维护模式'].map(x=><label className="switch-row" key={x}>{x}<input type="checkbox" defaultChecked={x!=='维护模式'} onChange={()=>notify(`${x} 状态已更新`)}/></label>)}</article></section><article className="panel"><h3>最近审计日志</h3><table><tbody>{[['12:42','admin@fastlink','创建卡项目 PRG-004'],['12:18','treasury@fastlink','执行资金调拨 $250,000'],['11:56','tenant.nova','轮换 API Key'],['11:31','compliance@fastlink','关闭风险案件 RSK-28']].map(r=><tr key={r[0]}><td>{r[0]}</td><td>{r[1]}</td><td>{r[2]}</td></tr>)}</tbody></table></article></>}
