import {useState} from 'react'
import {AlertTriangle,ArrowLeft,CheckCircle2,Play,RefreshCw,ShieldCheck,Users,WalletCards} from 'lucide-react'
import {actors,runAllScenarios,type ScenarioResult,type SimulationState} from './simulation'

type Props={onBack:()=>void}
export default function SimulationCenter({onBack}:Props){
 const[results,setResults]=useState<ScenarioResult[]>([]);const[state,setState]=useState<SimulationState|null>(null);const[running,setRunning]=useState(false)
 const run=()=>{setRunning(true);setTimeout(()=>{const out=runAllScenarios();setResults(out.results);setState(out.state);setRunning(false)},450)}
 const passed=results.filter(x=>x.status==='通过').length;const failed=results.filter(x=>x.status==='失败').length
 return <div className="sim-page"><header className="sim-top"><button onClick={onBack}><ArrowLeft/>返回SaaS后台</button><div><b>FastLink Integration Test Lab</b><span>多角色 · B端/C端 · 前端模拟数据</span></div><button className="run-btn" onClick={run} disabled={running}>{running?<RefreshCw className="spin"/>:<Play/>}{running?'正在运行':'运行全部场景'}</button></header><main className="sim-content">
 <section className="sim-hero"><div><small>END-TO-END DATA VALIDATION</small><h1>角色、权限、钱包、发卡、交易、清算一体化测试</h1><p>模拟真实租户及最终用户，检查租户隔离、RBAC、复式账本、余额变化、清算敞口、平台收入和风险案件。</p></div><ShieldCheck size={64}/></section>
 <section className="sim-metrics"><article><Users/><span>模拟角色</span><b>{actors.length}</b><small>6个B端 + 2个C端</small></article><article><Play/><span>测试场景</span><b>8</b><small>完整U卡业务链路</small></article><article><CheckCircle2/><span>通过</span><b>{passed}</b><small>自动一致性检查</small></article><article><AlertTriangle/><span>失败</span><b>{failed}</b><small>发现异常立即标红</small></article></section>
 <section className="sim-grid"><article className="sim-panel"><h2>模拟角色</h2><div className="actor-list">{actors.map(a=><div key={a.name}><span className={`actor-side ${a.side}`}>{a.side}</span><section><b>{a.name}</b><small>{a.tenant}</small></section><em>{a.permissions.length} 权限</em></div>)}</div></article><article className="sim-panel"><h2>最终数据快照</h2>{state?<div className="snapshot"><p><span>用户USDT余额</span><b>{state.userUsdt} USDT</b></p><p><span>用户卡余额</span><b>${state.userCard}</b></p><p><span>租户法币准备金</span><b>${state.tenantFiat}</b></p><p><span>平台收入</span><b>${state.platformRevenue}</b></p><p><span>待清算敞口</span><b>${state.settlementExposure}</b></p><p><span>复式账本</span><b>{state.ledgerDebit===state.ledgerCredit?'借贷平衡':'不平衡'}</b></p><p><span>风险案件</span><b>{state.riskCases}</b></p><p><span>卡片状态</span><b>{state.cardStatus}</b></p></div>:<div className="empty-test"><WalletCards/><p>点击“运行全部场景”生成数据结果</p></div>}</article></section>
 <article className="sim-panel scenarios"><div className="scenario-title"><div><h2>端到端场景执行结果</h2><p>按真实业务顺序运行，后一步使用前一步产生的数据。</p></div><button onClick={run}>{running?<RefreshCw className="spin"/>:<Play/>}重新运行</button></div>{results.length===0?<div className="empty-test"><Play/><p>尚未运行测试</p></div>:<div className="scenario-list">{results.map(r=><details key={r.id} open={r.status==='失败'}><summary><span className={r.status==='通过'?'pass':'fail'}>{r.status==='通过'?<CheckCircle2/>:<AlertTriangle/>}{r.status}</span><b>{r.id} · {r.name}</b><em>{r.channel} / {r.actor}</em><small>{r.duration}ms</small></summary><div><section><h4>执行步骤</h4>{r.steps.map(x=><p key={x}>→ {x}</p>)}</section><section><h4>一致性检查</h4>{r.checks.map(x=><p key={x}>✓ {x}</p>)}</section></div></details>)}</div>}</article>
 </main></div>
}
