import { useState } from 'react'
import { ArrowLeft, Building2, CreditCard, Database, FileCog, Landmark, Network, Palette, RefreshCw, ShieldCheck, Users, WalletCards, Webhook } from 'lucide-react'

type Props={notify:(s:string)=>void}
type AppDef={id:string;name:string;en:string;icon:any;summary:string;stats:[string,string][];actions:string[];rows:string[][];headers:string[]}

const apps:AppDef[]=[
{id:'tenant',name:'租户与组织中心',en:'Tenant / Partner / Sub-Issuer',icon:Building2,summary:'管理合作方、子发卡商、KYB、合同、保证金和组织层级。',stats:[['活跃租户','3'],['待审KYB','2'],['子发卡商','7']],actions:['新增租户','通过KYB','暂停租户'],headers:['租户','模式','KYB','状态'],rows:[['NovaPay Asia','White Label','已通过','运行中'],['Orbit Card Labs','OEM','已通过','运行中'],['BluePeak Finance','ODM','补件中','审核中']]},
{id:'white',name:'白标交付中心',en:'White Label / OEM / ODM',icon:Palette,summary:'管理品牌、域名、App、H5、卡面和交付任务。',stats:[['交付项目','4'],['待验收','2'],['已发布','1']],actions:['新建交付任务','发布品牌配置','提交验收'],headers:['项目','交付范围','进度','状态'],rows:[['NovaPay','App + H5 + Admin','100%','已发布'],['Orbit','App + Card Design','82%','验收中'],['BluePeak','Product + Tech + Ops','45%','配置中']]},
{id:'wallet',name:'钱包与账本',en:'Wallet & Double-entry Ledger',icon:WalletCards,summary:'管理USDT、多币种法币、冻结余额、内部账户和复式账本。',stats:[['USDT余额','$18.42M'],['法币余额','$3.86M'],['借贷差额','$0']],actions:['模拟入金','冻结余额','生成账本分录'],headers:['账户','币种','可用','冻结'],rows:[['NovaPay用户资金','USDT','10,240,000','0'],['Sponsor准备金','USD','3,860,000','120,000'],['清算过渡户','USD','428,600','428,600']]},
{id:'card',name:'卡片与发卡',en:'Card Issuing & Lifecycle',icon:CreditCard,summary:'管理卡项目、虚拟卡、实体卡、授权、冻结和Tokenization。',stats:[['已发卡','13,040'],['待激活','286'],['冻结卡','48']],actions:['发行虚拟卡','冻结卡片','创建Token'],headers:['卡项目','卡类型','发行量','状态'],rows:[['NovaPay Global U Card','虚拟+实体','7,310','生产模拟'],['Orbit Travel Card','虚拟卡','3,980','Sandbox'],['BluePeak Premium','实体卡','0','配置中']]},
{id:'pay',name:'支付与收单',en:'Payment & Merchant',icon:Network,summary:'管理扫码、商户支付、内部转账、代付和收款。',stats:[['今日支付','$384K'],['商户','126'],['成功率','98.9%']],actions:['创建商户','模拟扫码支付','发起代付'],headers:['交易','渠道','金额','状态'],rows:[['PAY-10082','QR Pay','$128.60','成功'],['PAY-10083','Internal Transfer','$2,500','处理中'],['PAY-10084','Merchant Acquiring','$860','成功']]},
{id:'fx',name:'换汇编排',en:'FX Orchestrator',icon:RefreshCw,summary:'管理USDT/法币报价、FOMO Pay、点差和流动性路由。',stats:[['今日换汇','$1.28M'],['平均点差','1.02%'],['成功率','99.4%']],actions:['获取报价','执行换汇','切换流动性通道'],headers:['订单','兑换对','金额','状态'],rows:[['FX-20881','USDT/USD','600','成功'],['FX-20882','USDT/MYR','2,500','成功'],['FX-20883','USDT/EUR','8,200','风控审核']]},
{id:'treasury',name:'Treasury与清算',en:'Treasury / Settlement',icon:Landmark,summary:'管理准备金、资金池、调拨、清算、对账和敞口。',stats:[['USDT资金池','$18.42M'],['法币准备金','$3.86M'],['待清算','$428.6K']],actions:['创建调拨','执行清算','运行对账'],headers:['批次','租户','金额','状态'],rows:[['STL-260719-A','NovaPay','$128,600','待执行'],['STL-260719-B','Orbit','$86,400','已完成'],['REC-260719-01','平台总账','$3,860,000','已平衡']]},
{id:'risk',name:'风险与合规',en:'Risk / AML / Compliance',icon:ShieldCheck,summary:'管理KYC、KYB、交易监控、制裁筛查和案件。',stats:[['开放案件','6'],['高风险','2'],['待审KYC','12']],actions:['分配案件','冻结账户','关闭案件'],headers:['案件','主体','评分','状态'],rows:[['RSK-001','Zhang Rui','92','待处理'],['RSK-002','BluePeak Finance','81','调查中'],['RSK-003','Muhammad Amir','68','待处理']]},
{id:'open',name:'开放平台',en:'API / Webhook / Sandbox',icon:Webhook,summary:'管理API Client、Scope、幂等、签名、回放和测试场景。',stats:[['API Clients','3'],['Webhook成功率','99.82%'],['Sandbox运行','1,284']],actions:['创建API Client','轮换密钥','回放Webhook'],headers:['客户端','环境','Scope','状态'],rows:[['NovaPay API','Production Mock','cards wallets','Active'],['Orbit API','Sandbox','cards kyc webhook','Active'],['BluePeak API','Sandbox','onboarding cards','Suspended']]},
{id:'billing',name:'计费与分成',en:'Billing / Revenue Share',icon:FileCog,summary:'管理SaaS订阅、发卡费、交易分成、换汇点差和账单。',stats:[['本月收入','$428.6K'],['待结算','$86.4K'],['账单','12']],actions:['创建费率模板','生成账单','执行分成'],headers:['租户','订阅费','交易分成','状态'],rows:[['NovaPay','$32,000','$84,200','待结算'],['Orbit','$18,000','$41,600','已结算'],['BluePeak','$12,000','$0','未启用']]}
]

export default function SubsystemApplications({notify}:Props){
 const[selected,setSelected]=useState<AppDef|null>(null)
 if(!selected)return <section className="subsystem-grid">{apps.map(a=>{const I=a.icon;return <article className="panel subsystem-card" key={a.id}><div className="subsystem-icon"><I/></div><div><h3>{a.name}</h3><b>{a.en}</b><p>{a.summary}</p><span className="status tag-运行中">可操作</span></div><button onClick={()=>setSelected(a)}>进入功能应用</button></article>})}</section>
 const I=selected.icon
 return <div className="subsystem-app"><button className="back-btn" onClick={()=>setSelected(null)}><ArrowLeft size={16}/>返回子系统中心</button><section className="hero app-hero"><div><span>{selected.en}</span><h2>{selected.name}</h2><p>{selected.summary}</p></div><I size={42}/></section><section className="module-stats">{selected.stats.map(([l,v])=><article className="metric-card" key={l}><span>{l}</span><strong>{v}</strong><small>模拟实时数据</small></article>)}</section><section className="action-bar">{selected.actions.map(a=><button key={a} onClick={()=>notify(`${selected.name}：${a}已在测试环境执行`)}>{a}</button>)}</section><article className="panel"><div className="panel-title"><div><h3>业务数据</h3><p>当前租户视角下的模拟数据，可执行状态变更与流程操作。</p></div></div><div className="table-scroll"><table><thead><tr>{selected.headers.map(h=><th key={h}>{h}</th>)}<th>操作</th></tr></thead><tbody>{selected.rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}<td><button className="text-btn" onClick={()=>notify(`已打开 ${selected.name} 记录详情`)}>查看</button><button className="text-btn" onClick={()=>notify(`已更新 ${selected.name} 记录状态`)}>处理</button></td></tr>)}</tbody></table></div></article></div>
}
