import { useMemo, useState } from 'react'
import { Building2, CheckCircle2, ChevronRight, CircleDollarSign, CreditCard, FileCheck2, KeyRound, LockKeyhole, Plus, ShieldCheck, Users, WalletCards, X } from 'lucide-react'

type Props={tenantId:string;onClose:()=>void;notify:(s:string)=>void}
type Tab='overview'|'onboarding'|'team'|'access'
type Member={id:string;name:string;email:string;role:string;status:'启用'|'待邀请'}
type TenantProfile={id:string;name:string;country:string;model:string;status:string;kyb:string;program:string;users:number;cards:number;volume:string;reserve:string;brand:string;domain:string;members:Member[]}

const tenantProfiles:TenantProfile[]=[
 {id:'TEN-1001',name:'NovaPay Asia',country:'新加坡',model:'White Label',status:'运行中',kyb:'已通过',program:'NovaPay Global U Card',users:12840,cards:7310,volume:'$4,286,000',reserve:'$1,920,000',brand:'NovaPay',domain:'app.novapay.asia',members:[{id:'M-101',name:'Lin Chen',email:'lin@novapay.asia',role:'Tenant Administrator',status:'启用'},{id:'M-102',name:'Sarah Lim',email:'sarah@novapay.asia',role:'Compliance Officer',status:'启用'},{id:'M-103',name:'Wei Jun',email:'wei@novapay.asia',role:'Operations Manager',status:'待邀请'}]},
 {id:'TEN-1002',name:'Orbit Card Labs',country:'马来西亚',model:'OEM',status:'运行中',kyb:'已通过',program:'Orbit Travel Card',users:6820,cards:3980,volume:'$1,865,000',reserve:'$860,000',brand:'Orbit',domain:'card.orbitlabs.my',members:[{id:'M-201',name:'Aiman Yusuf',email:'aiman@orbitlabs.my',role:'Tenant Administrator',status:'启用'},{id:'M-202',name:'Mei Ling',email:'mei@orbitlabs.my',role:'Developer',status:'启用'}]},
 {id:'TEN-1003',name:'BluePeak Finance',country:'香港',model:'ODM',status:'审核中',kyb:'补件中',program:'BluePeak Premium',users:0,cards:0,volume:'$0',reserve:'$0',brand:'BluePeak',domain:'待配置',members:[{id:'M-301',name:'Ada Wong',email:'ada@bluepeak.finance',role:'Tenant Administrator',status:'待邀请'}]},
 {id:'TEN-1004',name:'Astra Global',country:'阿联酋',model:'White Label',status:'暂停',kyb:'已通过',program:'Astra Global Card',users:3210,cards:1750,volume:'$642,000',reserve:'$280,000',brand:'Astra',domain:'pay.astraglobal.ae',members:[{id:'M-401',name:'Omar Malik',email:'omar@astraglobal.ae',role:'Tenant Administrator',status:'启用'}]}
]

const roleMatrix=[
 ['Tenant Administrator','租户内全部管理','用户、卡片、交易、团队、品牌','读写'],
 ['Compliance Officer','所属租户','KYB、KYC、AML案件、报告','审核'],
 ['Operations Manager','所属卡项目','用户、卡片、交易、工单','读写'],
 ['Treasury Viewer','所属租户','余额、清算、对账','只读'],
 ['Developer','Sandbox','API Client、Webhook、测试卡','读写']
]

function Status({value}:{value:string}){return <span className={`status tag-${value.replaceAll(' ','-')}`}>{value}</span>}

export default function TenantOperationsCenter({tenantId,onClose,notify}:Props){
 const[activeId,setActiveId]=useState(tenantId)
 const[tab,setTab]=useState<Tab>('overview')
 const[status,setStatus]=useState<Record<string,string>>({})
 const[kyb,setKyb]=useState<Record<string,string>>({})
 const[memberAdds,setMemberAdds]=useState<Record<string,Member[]>>({})
 const tenant=useMemo(()=>tenantProfiles.find(x=>x.id===activeId)??tenantProfiles[0],[activeId])
 const tenantStatus=status[tenant.id]??tenant.status
 const tenantKyb=kyb[tenant.id]??tenant.kyb
 const members=[...tenant.members,...(memberAdds[tenant.id]??[])]
 const updateStatus=()=>{const next=tenantStatus==='暂停'?'运行中':'暂停';setStatus(v=>({...v,[tenant.id]:next}));notify(`${tenant.name} 已${next==='暂停'?'暂停':'恢复'}`)}
 const approveKyb=()=>{setKyb(v=>({...v,[tenant.id]:'已通过'}));notify(`${tenant.name} KYB 已通过审核`)}
 const addMember=()=>{const next:Member={id:`M-${tenant.id.slice(-2)}${members.length+1}`,name:'New Operator',email:`operator${members.length+1}@${tenant.domain==='待配置'?'partner.test':tenant.domain}`,role:'Operations Manager',status:'待邀请'};setMemberAdds(v=>({...v,[tenant.id]:[...(v[tenant.id]??[]),next]}));notify('成员邀请已创建（Sandbox）')}
 return <div className="tenant-overlay"><div className="tenant-window"><header className="tenant-window-head"><div className="tenant-title"><span className="tenant-logo">{tenant.brand.slice(0,1)}</span><div><b>{tenant.name}</b><small>{tenant.id} · {tenant.model} · {tenant.country}</small></div></div><div className="tenant-head-actions"><select value={activeId} onChange={e=>{setActiveId(e.target.value);setTab('overview')}}>{tenantProfiles.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><Status value={tenantStatus}/><button className="tenant-close" onClick={onClose} aria-label="关闭"><X/></button></div></header><div className="tenant-layout"><aside className="tenant-nav"><p>合作方控制台</p>{([['overview','运营概况',Building2],['onboarding','入驻与KYB',FileCheck2],['team','团队成员',Users],['access','角色与数据权限',LockKeyhole]] as [Tab,string,typeof Building2][]).map(([id,label,Icon])=><button className={tab===id?'active':''} key={id} onClick={()=>setTab(id)}><Icon size={17}/>{label}<ChevronRight size={14}/></button>)}<div className="tenant-boundary"><LockKeyhole/><b>租户数据边界</b><span>当前页面只能访问 {tenant.name} 的用户、卡片、交易和配置。</span></div></aside><main className="tenant-content">
 {tab==='overview'&&<><section className="tenant-hero"><div><small>PARTNER / SUB-ISSUER CONTROL</small><h2>{tenant.name}</h2><p>{tenant.program} · {tenant.domain}</p></div><div><button className="secondary-btn" onClick={()=>notify('已生成租户运营报告')}>导出运营报告</button><button className={tenantStatus==='暂停'?'success-btn':'danger-btn'} onClick={updateStatus}>{tenantStatus==='暂停'?'恢复租户':'暂停租户'}</button></div></section><section className="tenant-metrics"><article><Users/><span>终端用户</span><b>{tenant.users.toLocaleString()}</b><small>仅当前租户</small></article><article><CreditCard/><span>已发行卡片</span><b>{tenant.cards.toLocaleString()}</b><small>虚拟卡 + 实体卡</small></article><article><CircleDollarSign/><span>累计交易额</span><b>{tenant.volume}</b><small>Sandbox 业务数据</small></article><article><WalletCards/><span>法币准备金</span><b>{tenant.reserve}</b><small>Sponsor Bank 视图</small></article></section><section className="tenant-two-col"><article className="panel"><div className="panel-title"><div><h3>项目运行状态</h3><p>合作方交付与业务服务状态</p></div></div>{[['KYB与合同',tenantKyb],['白标品牌','已发布'],['卡项目',tenant.cards?'运行中':'配置中'],['API环境',tenant.status==='审核中'?'Sandbox':'Production Mock'],['清算账户',tenant.reserve==='$0'?'待配置':'正常']].map(([label,value])=><div className="tenant-health" key={label}><span><CheckCircle2 size={16}/>{label}</span><Status value={value}/></div>)}</article><article className="panel"><div className="panel-title"><div><h3>近期待办</h3><p>需平台或租户管理员处理</p></div></div>{[['KYB资料更新',tenantKyb==='已通过'?'已完成':'需要补件'],['生产API密钥轮换','7天后到期'],['月度清算对账','待租户确认'],['卡项目限额复核','本周完成']].map(([name,value],i)=><button className="tenant-task" key={name} onClick={()=>notify(`${name} 已打开`)}><span>{i+1}</span><b>{name}</b><small>{value}</small><ChevronRight size={15}/></button>)}</article></section></>}
 {tab==='onboarding'&&<><section className="tenant-page-head"><div><h2>入驻、KYB与上线门禁</h2><p>完成所有必需检查后，合作方才可进入生产模拟环境。</p></div>{tenantKyb!=='已通过'&&<button className="success-btn" onClick={approveKyb}>批准 KYB</button>}</section><article className="panel onboarding-panel">{[['公司注册与受益人资料','公司证书、董事、UBO与地址证明','完成'],['制裁与PEP筛查','公司、董事及UBO筛查','完成'],['业务与资金来源','U卡业务模型、目标市场与资金来源','完成'],['服务合同与费用表','White Label / OEM / ODM服务范围','完成'],['保证金与准备金账户','Sponsor Bank准备金配置',tenant.reserve==='$0'?'待处理':'完成'],['品牌与技术验收','域名、App、H5、后台及API验收',tenant.domain==='待配置'?'待处理':'完成']].map(([name,desc,state],i)=><div className="onboarding-step" key={name}><span className={state==='完成'?'done':''}>{state==='完成'?<CheckCircle2/>:i+1}</span><div><b>{name}</b><small>{desc}</small></div><Status value={state}/><button onClick={()=>notify(`${name} 检查项已打开`)}>查看材料</button></div>)}</article></>}
 {tab==='team'&&<><section className="tenant-page-head"><div><h2>租户团队成员</h2><p>人员只能访问所属租户；平台管理员保留跨租户审计能力。</p></div><button className="primary-btn" onClick={addMember}><Plus size={16}/>邀请成员</button></section><article className="panel"><table><thead><tr><th>成员</th><th>邮箱</th><th>角色</th><th>数据范围</th><th>状态</th><th>操作</th></tr></thead><tbody>{members.map(m=><tr key={m.id}><td><b>{m.name}</b><small className="cell-sub">{m.id}</small></td><td>{m.email}</td><td>{m.role}</td><td>{tenant.name}</td><td><Status value={m.status}/></td><td><button className="text-btn" onClick={()=>notify(`${m.name} 权限编辑已打开`)}>编辑权限</button></td></tr>)}</tbody></table></article></>}
 {tab==='access'&&<><section className="tenant-page-head"><div><h2>角色与数据权限</h2><p>权限由角色、租户、卡项目、环境和操作风险共同约束。</p></div><button className="primary-btn" onClick={()=>notify('新角色向导已打开')}><Plus size={16}/>创建租户角色</button></section><article className="access-callout"><ShieldCheck/><div><b>跨租户隔离已启用</b><span>{tenant.name} 的管理员无法读取其他租户的用户、钱包、卡片、交易、API密钥和报表。</span></div></article><article className="panel"><table><thead><tr><th>角色模板</th><th>数据范围</th><th>模块</th><th>权限级别</th><th>操作</th></tr></thead><tbody>{roleMatrix.map(r=><tr key={r[0]}><td><b>{r[0]}</b></td><td>{r[1]}</td><td>{r[2]}</td><td><span className="permission-level"><KeyRound size={13}/>{r[3]}</span></td><td><button className="text-btn" onClick={()=>notify(`${r[0]} 权限矩阵已打开`)}>配置</button></td></tr>)}</tbody></table></article></>}
 </main></div></div></div>
}
