import { useMemo, useState } from 'react'
import { AppWindow, Check, CheckCircle2, ChevronRight, CreditCard, Globe2, Languages, LayoutTemplate, MonitorSmartphone, PackageCheck, Palette, Rocket, Settings2, Smartphone, X } from 'lucide-react'

type Props={projectId:string;onClose:()=>void;notify:(s:string)=>void}
type Tab='overview'|'brand'|'channels'|'card'|'release'
type ChannelKey='app'|'h5'|'admin'|'api'
type Project={id:string;tenant:string;brand:string;model:'White Label'|'OEM'|'ODM';scope:string;status:string;progress:number;primary:string;accent:string;domain:string;locales:string[];channels:Record<ChannelKey,boolean>}
type Draft={brand:string;primary:string;accent:string;domain:string;status:string;channels:Record<ChannelKey,boolean>}
type Task={name:string;owner:string;due:string;done:boolean}

const projects:Project[]=[
 {id:'WL-001',tenant:'NovaPay Asia',brand:'NovaPay',model:'White Label',scope:'App + H5 + Admin + Card',status:'已发布',progress:100,primary:'#0b1f2f',accent:'#35d5a3',domain:'app.novapay.asia',locales:['中文','English','Bahasa Melayu'],channels:{app:true,h5:true,admin:true,api:true}},
 {id:'WL-002',tenant:'Orbit Card Labs',brand:'Orbit',model:'OEM',scope:'App + Card Design + API',status:'验收中',progress:82,primary:'#151a38',accent:'#7c68ee',domain:'card.orbitlabs.my',locales:['English','Bahasa Melayu'],channels:{app:true,h5:false,admin:true,api:true}},
 {id:'WL-003',tenant:'BluePeak Finance',brand:'BluePeak',model:'ODM',scope:'Product + Tech + Operations',status:'配置中',progress:45,primary:'#10283b',accent:'#2aa9ff',domain:'待配置',locales:['中文','English'],channels:{app:true,h5:true,admin:true,api:false}}
]

const initialTasks:Record<string,Task[]>={
 'WL-001':[{name:'品牌资产确认',owner:'Brand Team',due:'已完成',done:true},{name:'App与H5验收',owner:'Delivery Team',due:'已完成',done:true},{name:'卡面与制卡文件',owner:'Card Program',due:'已完成',done:true},{name:'生产模拟发布',owner:'Platform Ops',due:'已完成',done:true}],
 'WL-002':[{name:'品牌资产确认',owner:'Orbit',due:'7月20日',done:true},{name:'App主题与语言',owner:'Delivery Team',due:'7月21日',done:true},{name:'Mastercard卡面验收',owner:'Card Program',due:'7月22日',done:false},{name:'API联调与验收',owner:'Developer',due:'7月23日',done:false}],
 'WL-003':[{name:'产品范围确认',owner:'Product',due:'7月21日',done:true},{name:'品牌资产与域名',owner:'BluePeak',due:'7月23日',done:false},{name:'App/H5/Admin配置',owner:'Delivery Team',due:'7月26日',done:false},{name:'运营流程验收',owner:'Operations',due:'7月28日',done:false}]
}

const channelMeta:Record<ChannelKey,{name:string;desc:string;icon:typeof Smartphone}>={
 app:{name:'Mobile App',desc:'iOS / Android 白标钱包与卡片应用',icon:Smartphone},
 h5:{name:'H5 Portal',desc:'移动网页、开户、KYC与卡片服务',icon:MonitorSmartphone},
 admin:{name:'Tenant Admin',desc:'租户运营、用户、卡片、交易与报表',icon:AppWindow},
 api:{name:'Partner API',desc:'API Client、Webhook、Sandbox与集成文档',icon:Globe2}
}

function Badge({value}:{value:string}){return <span className={`status tag-${value.replaceAll(' ','-')}`}>{value}</span>}

export default function WhiteLabelDeliveryCenter({projectId,onClose,notify}:Props){
 const[selectedId,setSelectedId]=useState(projects.some(x=>x.id===projectId)?projectId:projects[0].id)
 const[tab,setTab]=useState<Tab>('overview')
 const[drafts,setDrafts]=useState<Record<string,Draft>>(()=>Object.fromEntries(projects.map(p=>[p.id,{brand:p.brand,primary:p.primary,accent:p.accent,domain:p.domain,status:p.status,channels:{...p.channels}}])))
 const[tasks,setTasks]=useState(initialTasks)
 const[cardFinish,setCardFinish]=useState('Matte Black')
 const project=useMemo(()=>projects.find(x=>x.id===selectedId)!,[selectedId])
 const draft=drafts[selectedId]
 const projectTasks=tasks[selectedId]
 const completed=projectTasks.filter(x=>x.done).length
 const progress=Math.round(completed/projectTasks.length*100)
 const patchDraft=(patch:Partial<Draft>)=>setDrafts(v=>({...v,[selectedId]:{...v[selectedId],...patch}}))
 const toggleChannel=(key:ChannelKey)=>patchDraft({channels:{...draft.channels,[key]:!draft.channels[key]}})
 const toggleTask=(index:number)=>{setTasks(v=>({...v,[selectedId]:v[selectedId].map((x,i)=>i===index?{...x,done:!x.done}:x)}));notify('交付任务状态已更新')}
 const saveBrand=()=>notify(`${draft.brand} 品牌配置已保存到 Sandbox`)
 const submitAcceptance=()=>{patchDraft({status:'验收中'});notify(`${draft.brand} 已提交合作方验收`)}
 const publish=()=>{if(progress<100){notify('还有未完成的交付任务，暂不能发布');return}patchDraft({status:'已发布'});notify(`${draft.brand} 已发布到生产模拟环境`)}
 return <div className="white-overlay"><div className="white-window"><header className="white-head"><div className="white-heading"><span className="white-mark" style={{background:draft.accent}}>{draft.brand.slice(0,1)}</span><div><b>{draft.brand} Delivery Center</b><small>{project.id} · {project.model} · {project.tenant}</small></div></div><div className="white-head-actions"><select value={selectedId} onChange={e=>{setSelectedId(e.target.value);setTab('overview')}}>{projects.map(x=><option value={x.id} key={x.id}>{x.brand} · {x.model}</option>)}</select><Badge value={draft.status}/><button onClick={onClose} aria-label="关闭"><X/></button></div></header><div className="white-layout"><aside className="white-nav"><p>交付项目管理</p>{([['overview','项目总览',LayoutTemplate],['brand','品牌与域名',Palette],['channels','交付渠道',MonitorSmartphone],['card','卡面设计',CreditCard],['release','验收与发布',Rocket]] as [Tab,string,typeof Palette][]).map(([id,label,Icon])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><Icon size={17}/>{label}<ChevronRight size={14}/></button>)}<div className="white-scope"><PackageCheck/><b>{project.model} 交付范围</b><span>{project.scope}</span></div></aside><main className="white-content">
 {tab==='overview'&&<><section className="white-hero" style={{background:`linear-gradient(135deg,${draft.primary},${draft.accent}aa)`}}><div><small>FASTLINK WHITE-LABEL DELIVERY</small><h2>{draft.brand}</h2><p>{project.scope} · {draft.domain}</p></div><div className="white-progress"><b>{progress}%</b><span>交付完成度</span></div></section><section className="white-metrics"><article><LayoutTemplate/><span>合作模式</span><b>{project.model}</b><small>{project.tenant}</small></article><article><Languages/><span>已配置语言</span><b>{project.locales.length}</b><small>{project.locales.join(' · ')}</small></article><article><MonitorSmartphone/><span>启用渠道</span><b>{Object.values(draft.channels).filter(Boolean).length}</b><small>App / H5 / Admin / API</small></article><article><CheckCircle2/><span>交付任务</span><b>{completed}/{projectTasks.length}</b><small>按验收门禁管理</small></article></section><section className="white-two"><article className="panel"><div className="panel-title"><div><h3>渠道交付状态</h3><p>当前项目的产品与技术交付范围</p></div></div>{(Object.keys(channelMeta) as ChannelKey[]).map(key=>{const meta=channelMeta[key];const Icon=meta.icon;return <div className="channel-line" key={key}><Icon/><div><b>{meta.name}</b><small>{meta.desc}</small></div><Badge value={draft.channels[key]?'已启用':'未启用'}/></div>})}</article><article className="panel"><div className="panel-title"><div><h3>当前交付任务</h3><p>点击任务可更新完成状态</p></div></div>{projectTasks.map((task,i)=><button className={`delivery-task ${task.done?'done':''}`} onClick={()=>toggleTask(i)} key={task.name}><span>{task.done?<Check/>:i+1}</span><div><b>{task.name}</b><small>{task.owner} · {task.due}</small></div><Badge value={task.done?'完成':'待处理'}/></button>)}</article></section></>}
 {tab==='brand'&&<><section className="white-page-head"><div><h2>品牌、主题与域名</h2><p>所有配置仅作用于当前租户，不影响 FastLink 平台或其他合作方。</p></div><button className="white-primary" onClick={saveBrand}>保存品牌配置</button></section><section className="brand-grid"><article className="panel brand-form"><label>品牌名称<input value={draft.brand} onChange={e=>patchDraft({brand:e.target.value})}/></label><label>白标域名<input value={draft.domain} onChange={e=>patchDraft({domain:e.target.value})}/></label><div className="color-fields"><label>主背景色<input type="color" value={draft.primary} onChange={e=>patchDraft({primary:e.target.value})}/><code>{draft.primary}</code></label><label>品牌强调色<input type="color" value={draft.accent} onChange={e=>patchDraft({accent:e.target.value})}/><code>{draft.accent}</code></label></div><label>启用语言<div className="language-chips">{['中文','English','Bahasa Melayu','Tiếng Việt','ไทย','日本語','한국어'].map(x=><button className={project.locales.includes(x)?'selected':''} key={x} onClick={()=>notify(`${x} 语言包配置已打开`)}>{x}</button>)}</div></label></article><article className="brand-preview" style={{background:`linear-gradient(160deg,${draft.primary},${draft.accent})`}}><small>LIVE BRAND PREVIEW</small><span className="preview-logo">{draft.brand.slice(0,1)}</span><h3>{draft.brand}</h3><p>Global Wallet & U Card</p><div><b>$12,840.50</b><small>Total Assets</small></div><button style={{background:draft.accent}}>Deposit</button><em>{draft.domain}</em></article></section></>}
 {tab==='channels'&&<><section className="white-page-head"><div><h2>产品渠道与交付范围</h2><p>按合作模式开启 App、H5、租户后台和开放API。</p></div><button className="white-primary" onClick={()=>notify('渠道配置已保存')}>保存渠道配置</button></section><section className="channel-grid">{(Object.keys(channelMeta) as ChannelKey[]).map(key=>{const meta=channelMeta[key];const Icon=meta.icon;const enabled=draft.channels[key];return <article className={`channel-card ${enabled?'enabled':''}`} key={key}><Icon/><div><h3>{meta.name}</h3><p>{meta.desc}</p></div><label className="white-switch"><input type="checkbox" checked={enabled} onChange={()=>toggleChannel(key)}/><i/><span>{enabled?'已纳入交付':'未启用'}</span></label><button onClick={()=>notify(`${meta.name} 详细配置已打开`)}><Settings2/>配置模块</button></article>})}</section></>}
 {tab==='card'&&<><section className="white-page-head"><div><h2>实体卡与虚拟卡卡面</h2><p>配置品牌卡面、材质、卡组织标识和制卡文件。</p></div><button className="white-primary" onClick={()=>notify('卡面版本已提交审核')}>提交卡面审核</button></section><section className="card-design-grid"><article className="card-canvas" style={{background:`linear-gradient(135deg,${draft.primary},${draft.accent})`}}><div><span className="card-brand">{draft.brand}</span><small>GLOBAL U CARD</small></div><div className="card-chip"/><b>••••&nbsp; ••••&nbsp; ••••&nbsp; 8842</b><footer><span>CARDHOLDER NAME</span><strong>mastercard</strong></footer></article><article className="panel card-options"><h3>卡面规格</h3><label>卡片材质<select value={cardFinish} onChange={e=>setCardFinish(e.target.value)}><option>Matte Black</option><option>Glossy PVC</option><option>Metal Premium</option><option>Eco Recycled</option></select></label><label>卡片类型<select><option>虚拟卡 + 实体卡</option><option>仅虚拟卡</option><option>仅实体卡</option></select></label><label>卡组织<select><option>Mastercard</option><option disabled>Visa（待配置）</option></select></label><div className="spec-list"><span>当前材质<b>{cardFinish}</b></span><span>卡片尺寸<b>ISO/IEC 7810 ID-1</b></span><span>安全区域<b>已通过模板检查</b></span></div></article></section></>}
 {tab==='release'&&<><section className="white-page-head"><div><h2>交付验收与环境发布</h2><p>所有任务完成并通过租户验收后，才能发布生产模拟版本。</p></div><Badge value={draft.status}/></section><article className="panel release-panel"><div className="release-summary"><div className="release-ring" style={{'--progress':`${progress*3.6}deg`} as React.CSSProperties}><span>{progress}%</span></div><div><h3>{draft.brand} 发布门禁</h3><p>{completed} / {projectTasks.length} 项任务已完成</p></div><div className="release-actions"><button onClick={submitAcceptance}>提交合作方验收</button><button className="publish" disabled={progress<100} onClick={publish}>发布生产模拟</button></div></div>{projectTasks.map((task,i)=><div className="release-row" key={task.name}><button className={task.done?'done':''} onClick={()=>toggleTask(i)}>{task.done?<Check/>:i+1}</button><div><b>{task.name}</b><small>负责人：{task.owner} · 计划：{task.due}</small></div><Badge value={task.done?'已通过':'待处理'}/></div>)}</article></>}
 </main></div></div></div>
}
